name = "Statech Industry 1.21.1 Unofficial"
author = "Static Void & Purple Dino"
version = "0.1.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e02456d5b88bb08d9bed23fa8aa388af9e1af0a47110e0be7250aab6a675c7bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
