name = "Statech Industry 1.21.1 Unofficial"
author = "Static Void & Purple Dino"
version = "0.1.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67adf854202454da3b88017a4363ceeabbf9f047a427c4bc7023d65dd6292c41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
