enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = true
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableFtbQuestsIntegration = false
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = false
removeIndustrialistTrades = true
maxDistillationTowerHeight = 9
enableInterMachineConnectedTextures = false
armorHudYPosition = 4
baseItemPipeTransfer = 16
stonecutterToCuttingMachine = true
compostableToPlantOil = true
